version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
<<<<<<< HEAD
    - "5050:8000"

=======
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
>>>>>>> backend

  ui:
    build: ./ui
    ports:
      - "5173:5173"   # ⬅️ Add this or update from 5173
    stdin_open: true
    tty: true
    depends_on:
      - backend