version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  ui:
    build: ./ui
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend